In [1]:
# Import the random module.
import random

In [2]:
random.randint(-90,90)

35

In [3]:
random.random()

0.41403660087383876

In [5]:
random_number = random.randint(-90,89) + random.random()
random_number

-79.53749708813268

In [6]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1
print (latitudes)

[51.741671289273036, 57.46664218718814, -39.53388780358951, 74.90450157477153, -70.66161851532075, 2.5599763873822936, -19.391651470436326, -12.50261972777384, 83.25307178165694, 14.027661266874452]


In [7]:
x = 1
longitudes = []
while x < 11:
    random_lat = random.randint(-180, 179) + random.random()
    longitudes.append(random_lat)
    x += 1
print (longitudes)

[23.900139993307818, 143.30886291321914, -49.76909882296296, 158.5322948571458, -124.77243335627256, 47.34181792167662, -25.93986967276731, 17.583523562181234, -113.24040055186629, -48.4568499180074]


In [8]:
random.randrange(-90, 90, step=1)

77

In [9]:
random.randrange(-90, 90, step=3)

-18

In [10]:
random.uniform(-90, 90)

-57.31146671683432

In [11]:
# Import the NumPy module.
import numpy as np

In [12]:
np.random.uniform(-90.000, 90.000)

35.049224050197

In [13]:
np.random.uniform(low=-90, high=90)

58.06092679988885

In [14]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 53.10165194, -13.9577278 ,   6.736391  ,  89.06190364,
        73.20358416,  63.8840283 ,  86.55559581, -17.73384975,
       -71.82513119, -15.11815611, -40.84985386,  70.12571127,
       -27.1682515 , -73.28497025,  35.94255667,  28.54050829,
        37.9473641 , -80.80753214, -25.45984075,  81.34760858,
        74.01613827,  15.97994795,  71.84370592,  50.64502588,
        33.11194604, -54.11597779,  69.7837479 , -32.29367863,
       -74.1032245 ,  51.83601852,  67.64062705,  27.82096401,
       -65.33342989, -34.26868473, -17.75498907, -10.73895149,
       -72.81208677,  66.39979099, -13.07509965,  74.8883585 ,
        72.74932973,  78.92497559, -19.28130836,  35.98319586,
        35.04457693,  72.30916064, -69.43628699,  66.27021526,
         3.01207871, -19.87407746])

In [15]:
# Import timeit.
import timeit

In [16]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 74.95611408, -82.67498422,  33.58340932, ..., -12.54090153,
       -43.6308073 ,  -4.55086791])

In [17]:
%timeit
np.random.uniform(-90.000, 90.000, size=1500)


array([-61.90074564, -10.30793561,  41.29616758, ..., -78.46308463,
        12.41895192,  60.9333753 ])

In [18]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

27 µs ± 2.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
